#!/usr/bin/env bash
# Configures a new ubuntu machine by installing
# Nginx where it should be listening on port 80
# Serve a page that would return a Hello World string
#

# Update package list and install nginx
sudo apt-get update
sudo apt-get -y install nginx

# Configure nginx to listen on port 80
sudo sed -i 's/# listen 80/listen 80/' /etc/nginx/sites-available/default

# Create a simple HTML page with the string "Hello World!"
sudo sh -c 'echo "Hello World!" > /var/www/html/index.html'

# Restart nginx
sudo /etc/init.d/nginx restart
