#!/usr/bin/env bash
# This script installs and sets up a load balancer
sudo apt-get -y update
sudo apt-get -y install haproxy
sudo chown -R "$USER:$USER" /etc/haproxy/
printf %s "
#frontend configuration
frontend http-in
    bind *:80
    mode http
    default_backend servers
# Backend configuration
backend servers
    balance roundrobin
    server server1 18.206.206.219:80 check
    server server2 100.25.118.58:80 check
" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart
