#!/usr/bin/env bash
# prints best school using while loop

i=0
while [ "$i" -lt 10 ]; do

 # if 3 bad luck elif 7 good luck
  if [ "$i" -eq 3 ]; then
    echo "bad luck"
  elif [ "$i" -eq 7 ]; then
    echo "good luck"
  else
    echo "Best School"
  fi
  ((i++))
done
